### ISSUE TITLE
Error building on PowerPC due to intrinsics

### ISSUE THREAD

**Issue by mlawsonca** [ravendb/ravendb-cpp-client#26]
I am attempting to build on POWER9 but run into the following error:
```
xxhash.hpp: In function 'xxh::vec_t<N> xxh::vec_ops::set1(int)':
/Path/ravendb-cpp-client/External/xxhash/repository/include/xxhash.hpp:701:12: error: there are no arguments to '_mm256_set1_epi32' that depend on a template parameter, so a declaration of '_mm256_set1_epi32' must be available [-fpermissive]
  701 |     return _mm256_set1_epi32(a)
```
My architecture doesn't define _mm256_set1_epi32. How can I proceed with the build?

**Comment by ayende** [comment]
I'm afraid that I don't have a POWER9 machine to test this, but can you test this?
https://github.com/Cyan4973/xxHash

If this works, you can replace the use of xxhash with this.

**Comment by mlawsonca** [comment]
It's not a drop in change since there are API changes between the xxHash library and xxhash, but I was able to build it using xxHash. Thank you!

**Comment by ayende** [comment]
Would you be able to provide a PR for this ?
