### ISSUE TITLE
Installation script build dir not existing

### ISSUE THREAD

**Issue by twingoof** [ravendb/ravendb-cpp-client#28]
The installation script is looking for `${BUILDDIR}` when calling push on line 297 (which is set to `cmake-build-release` in the script) but the folder doesn't exist in the repository causing the script the script to stop and returning an error. It could be a good improvement to make the script create it automatically even if this isn't a long problem to solve.

**Comment by ayende** [comment]
Would you be able to send a PR for this?

**Comment by twingoof** [comment]
Here you go

**Comment by ayende** [comment]
Thanks!
